// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMT.Infrastructure.Persistence;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SMTDbContext))]
    [Migration("20260105135519_InitialSeedData")]
    partial class InitialSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SMT.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Main control PCB for ASMPT placement system",
                            Length = 120.0,
                            Name = "Control Board PCB",
                            Width = 80.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Power supply PCB for SMT machine",
                            Length = 150.0,
                            Name = "Power Board PCB",
                            Width = 100.0
                        });
                });

            modelBuilder.Entity("SMT.Domain.Entities.BoardComponent", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BoardComponents");

                    b.HasData(
                        new
                        {
                            BoardId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ComponentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 20
                        },
                        new
                        {
                            BoardId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ComponentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Quantity = 10
                        },
                        new
                        {
                            BoardId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ComponentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 1
                        },
                        new
                        {
                            BoardId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ComponentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 15
                        },
                        new
                        {
                            BoardId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ComponentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Quantity = 8
                        });
                });

            modelBuilder.Entity("SMT.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Standard 10k Ohm SMD resistor",
                            Name = "Resistor 10kΩ"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Ceramic capacitor 100nF",
                            Name = "Capacitor 100nF"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Main control IC for PCB logic",
                            Name = "Microcontroller IC"
                        });
                });

            modelBuilder.Entity("SMT.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "SMT production order for ASMPT demo line",
                            Name = "ASMPT-SMT-ORDER-001",
                            OrderDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SMT.Domain.Entities.OrderBoard", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId", "BoardId");

                    b.HasIndex("BoardId");

                    b.ToTable("OrderBoards");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            BoardId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            OrderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            BoardId = new Guid("00000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("SMT.Domain.Entities.BoardComponent", b =>
                {
                    b.HasOne("SMT.Domain.Entities.Board", "Board")
                        .WithMany("BoardComponents")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMT.Domain.Entities.Component", "Component")
                        .WithMany("BoardComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("SMT.Domain.Entities.OrderBoard", b =>
                {
                    b.HasOne("SMT.Domain.Entities.Board", "Board")
                        .WithMany("OrderBoards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMT.Domain.Entities.Order", "Order")
                        .WithMany("OrderBoards")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SMT.Domain.Entities.Board", b =>
                {
                    b.Navigation("BoardComponents");

                    b.Navigation("OrderBoards");
                });

            modelBuilder.Entity("SMT.Domain.Entities.Component", b =>
                {
                    b.Navigation("BoardComponents");
                });

            modelBuilder.Entity("SMT.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderBoards");
                });
#pragma warning restore 612, 618
        }
    }
}
